export const FETCHING_BEGINNER = 'FETCHING_BEGINNER';
export const FETCH_BEGINNER = 'FETCH_BEGINNER';
export const CREATING_BEGINNER = 'CREATING_BEGINNER';
export const CREATE_BEGINNER = 'CREATE_BEGINNER';
